spring.application.name=ZuPayBackend

# MySQL Cloud / TiDB Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# Seed data
# Keep this as 'always' to ensure your new bill data is inserted!
spring.sql.init.mode=always

# Server Config for Render Compatibility
server.address=0.0.0.0
server.port=${PORT:8080}